version: "3.6"
services:
  app:
    image: node:10
    env_file: .env
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: yarn run dev
    networks:
      - default
